---
- name: VScode and extensions
  hosts: localhost

  tasks:
    - name: Install core vscode packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - visual-studio-code

    - name: Install ansible-dev-tools using pipx
      ansible.builtin.pip:
        name: ansible-dev-tools
        executable: pipx
        state: present
        # Optional: use a specific version
        # version: 25.8.4.dev6

    - name: Install Drupal supporting vscode extensions
      ansible.builtin.shell:
        cmd: code --install-extension "{{ item }}"
        executable: /bin/bash
      with_items:
        - editorconfig.editorconfig
        - redhat.ansible
        - trunk.io
        - vscode.php-language-features
        - valeryanm.vscode-phpsab
        - bmewburn.vscode-intelephense-client
        - devsense.phptools-vscode
        - bradlc.vscode-tailwindcss
        - marcostazi.vs-code-drupal
        #- xdebug/vscode-php-debug
